import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import AllOrdersScreen from '../screens/AllOrdersScreen';
import AllUsersScreen from '../screens/AllUsersScreen';
import DashboardScreen from '../screens/DashboardScreen';
import UpdateProductsScreen from '../screens/UpdateProductsScreen';

export default function Home() {
  const [action, setAction] = useState(0);

  function showActionTab() {
    console.log('run');
    if (action === 0) {
      return <DashboardScreen />;
    } else if (action === 1) {
      return <UpdateProductsScreen />;
    } else if (action === 2) {
      return <AllOrdersScreen />;
    } else {
      return <AllUsersScreen />;
    }
  }
  return (
    <div className='h-screen fixed w-screen'>
      <Head>
        <title>Tejdharart | ADMIN</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='grid grid-cols-5 h-screen w-full '>
        <div className='col-span-1  bg-amber-400'>
          <div className='flex justify-start'>
            <Image
              src='/logo_tejdharart.jpg'
              width={100}
              height={100}
              objectFit='contain'
              className='p-2'
            />
          </div>

          <div className='px-2 mt-3 flex flex-col w-full'>
            <div
              className='px-2 py-2 text-black font-semibold rounded-md hover:bg-amber-500 cursor-pointer'
              onClick={() => setAction(0)}
            >
              Dashboard
            </div>
            <div className='h-[0.2px] bg-gray-300 w-full'></div>
            <div
              className='px-2 py-2 text-black font-semibold rounded-md hover:bg-amber-500 cursor-pointer'
              onClick={() => setAction(1)}
            >
              Update Products
            </div>
            <div className='h-[0.2px] bg-gray-300 w-full'></div>
            <div
              className='px-2 py-2 text-black font-semibold rounded-md hover:bg-amber-500 cursor-pointer'
              onClick={() => setAction(2)}
            >
              All Orders
            </div>
            <div className='h-[0.2px] bg-gray-300 w-full'></div>

            <div
              className='px-2 py-2 text-black font-semibold rounded-md hover:bg-amber-500 cursor-pointer'
              onClick={() => setAction(3)}
            >
              All Users
            </div>
          </div>
        </div>
        <div className='col-span-4 p-4 overflow-y-auto'>{showActionTab()}</div>
      </div>
    </div>
  );
}
