import Head from 'next/head';
import Image from 'next/image';

export default function Home({ products }) {
  return (
    <div className='md:h-screen md:fixed lg:h-screen lg:fixed xl:h-screen xl:fixed w-screen'>
      <Head>
        <title>Tejdharart | ADMIN</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo_tejdharart.jpg' />
      </Head>
      <div>
        <div className='p-2'>
          <p className='text-red-700 text-xl mt-2 font-semibold'>
            ERROR<span className='text-sm ml-2'>(subscription-terminated)</span>
          </p>
          <p>Subscription terminated until further payment is initiated!</p>
        </div>
      </div>
    </div>
  );
}
